#!/bin/sh

safe_copy_existing_paths() {
	echo "np: $# 1:$1 2:$2";
	if [ $# -ne 2 ]; then
		echo "Must call with 2 file paths";
		exit 1;
	elif [ ! -f $1 ]; then
		echo "$1 is not a file";
		return 1;
	elif [ ! -f $2 ]; then
		echo "$2 is not a file";
		return 1;
	fi
	
	echo "Copying $1 to $2";
	
	rtnval=$(cp -r $1 $2);
	return $rtnval;
}

# sloppy way to test my dumb functions
testfn(){
	safe_copy_existing_paths test1 test2

	if [ $? -gt 0 ]; then
		echo "failed";
	fi


	safe_copy_existing_paths bad1 bad2

	if [ $? -gt 0 ]; then
		echo "failed";
	fi
}

testfn
