#!/bin/bash
#
# get_creds
#

# Definitely one of the stupidest, most unsafe way to handle credentials

create_secrets_file() {
        local location=$1
        cat > $location <<- EOF
        export USERNAME=$USERNAME
        export PASSWORD=$PASSWORD
EOF
}

get_creds() {
        # sets local variables to empty strings
        local USERNAME=
        local PASSWORD=

        echo "Please enter credentials:"
        echo -n "Username: "
        read USERNAME
        
        echo -n "Password: "
        # -s (secret) suppress keypresses
        read -s PASSWORD

        echo
        create_secrets_file "$FILENAME"
        echo "Created secrets file: $FILENAME"
}

load_credentials() {
        if [ ! -r $FILENAME ]; then
                get_creds
        fi
        source $FILENAME
}

load_credentials
